### PR TITLE
Update git definitions

### PR DESCRIPTION
**Pull request by Erica42**
Fixed typo and light editing

### CODE REVIEW

**Comment by Erica42** [comment]
@Bontgoy Yay a typo for making me do a second pull request before I read the second release.

**Comment by Bontgoy** [comment]
:shipit: @Erica42   Just make sure that in the future, you wait for my response before merging.

Thanks!

**Comment by Erica42** [comment]
Do I need to wait for your response for all future merges, or just ones
where I am supposed to call you out on a comment?

**Comment by Bontgoy** [comment]
Just PRs you tag me in

Thanks!

**Pull request merged**
